# Generated by Django 4.2.5 on 2023-10-31 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(default=18, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='aim',
            field=models.CharField(default=18, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.TextField(default=20),
            preserve_default=False,
        ),
    ]
