# Generated by Django 4.2.5 on 2023-11-02 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
